### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by waioli1223** [waioli1223/chat-space#17]
#IPアドレス
52.196.92.152

**Comment by yasunamiura** [comment]
村上さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①サイドバーにあるグループ名と最新メッセージの青い下線を消しましょう**
<img width="293" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/78954511-5fcdab80-7b17-11ea-9a9a-91e9ac877b9c.png">
模範
<img width="294" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/78954581-87247880-7b17-11ea-8b2f-b08caba4d8be.png">



修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by waioli1223** [comment]
ご確認ありがとうございます。失礼致しました。
色が似ていて気付きませんでした。
修正致しました。ご確認お願い致します。

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by waioli1223** [comment]
一安心です。。
ありがとうございました。
